Delete update functionality
OksanaPR/ContactListAPI pull request #3
Opened 2020-09-09 09:48 UTC by OksanaPR

The final pull request to master for delete-update-functionality
1. File names follow the same file naming convention
2. Update, delete and delete bu id moved to database.py

2020-09-10 07:20 UTC, francolaiuppa requested changes
Hi @OksanaPR , we're almost there! Please apply the feedback, and if you have any further doubts we can solve it together on our call.
 
After we merge this, we will be ready for adding our first unit test OR implementing the API. Personally, I think the unit test will give you more value right now.

Keep up the good work!!

2020-09-10 07:20 UTC, francolaiuppa commented on README.md
>  - Allows deleting a Contact
```suggestion
```

2020-09-10 07:20 UTC, francolaiuppa commented on README.md
> +### delete_contact_by_id.py
```suggestion
### delete_contacts.py
```

2020-09-10 07:20 UTC, francolaiuppa commented on README.md
> +Usage: `python deleteContacts.py`
```suggestion
Usage: `python delete_contacts.py`
```

2020-09-10 07:20 UTC, francolaiuppa commented on README.md
>  2. You can then run any of the following commands
```suggestion
2. You can then run any of the commands described above.
```

We might also want to move the command explanation below, as it was before? lets discuss this

2020-09-10 07:20 UTC, francolaiuppa commented on database.py
> +def update_contacts(c, tableName, id, phone):
Since this function only updates the phone number, it'd be better if the name would represent that.

Additionally, since we are only updating the phone number, and the phone number is always stored in `ContactList`, we should not need to give it the table name. 

In general, the fewer arguments (also called parameters) we have, the better. 

Tip: You already applied this feedback in the `delete_by_id` function.

```suggestion
def update_phone_number(c, id, phone):
    c.execute('UPDATE ContactList SET phoneNumber = ? WHERE ROWID = ?', (phone, id))
```

2020-09-10 07:20 UTC, francolaiuppa commented on database.py
> +    c.execute('UPDATE ' + tableName + ' SET phoneNumber = ? WHERE ROWID = ?', (phone, id))
```suggestion
```

2020-09-10 07:20 UTC, francolaiuppa commented on delete_contacts.py
> +delete_all_contacts()
loving this, so short!

2020-09-10 07:20 UTC, francolaiuppa commented on update_contacts.py
> +    database.update_contacts(c, 'ContactList', id, phone)
Remember to change this `update_contacts` to match the comments above.

2020-09-10 07:20 UTC, francolaiuppa commented on update_contacts.py
> +    database.update_contacts(c, 'ContactList', id, phone)
Also, please take a look at this line: Here we are updating the `ContactList` table, but on lines 11 and 12 we are doing the validation. 

We should do the validation **before** we try to update in the database, otherwise people will be able to save whatever they want to the database. Does this make sense?

In fact, to make the exercise simpler, lets remove the requirement of "empty" phone number.

2020-09-10 07:20 UTC, francolaiuppa commented on database.py
> +def delete_by_id(c, tableName, id):
Why have you deleted the `select_by_id` function? Remember you are using it on `get_contact_by_id.py`

Additionally, maybe we can simplify it? What about:
```
def select_by_id(c, tableName, id):
    c.execute('SELECT * FROM ' + tableName + ' WHERE ROWID =(?)', id)
```

2020-09-12 10:56 UTC, OksanaPR reviewed
As we discussed everything and I am fine with it, could you please approve/merge this pull request? I cannot do this, it shows me an error "Pull request author cannot Approve it's own pull request". Thanks

2020-09-13 21:00 UTC, merged